# Generated by Django 3.1.3 on 2021-12-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_room',
            new_name='class_room_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='class_room1',
            new_name='class_room1_id',
        ),
    ]
