# Generated by Django 3.1.3 on 2021-12-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clg', '0002_auto_20211227_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_room1_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_room_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clg.class_room'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clg.class_room'),
        ),
    ]
