# Generated by Django 3.2.9 on 2021-12-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_room',
            fields=[
                ('class_room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_room_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_address', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_mobile_no', models.BigIntegerField()),
                ('class_room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffDemo.class_room')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_address', models.CharField(blank=True, max_length=100, null=True)),
                ('student_mobile_no', models.BigIntegerField()),
                ('class_room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffDemo.class_room')),
            ],
        ),
    ]
